name: ci

on:
  push:
    branch: master
  pull_request:
    branch: master

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [20]

    name: safe-cipher (NodeJS ${{ matrix.node }})

    steps:
    - name: Checkout Git repository
      uses: actions/checkout@v4

    - name: Setup NodeJS environment
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}

    - name: Run tests
      run: |
        npm install
        npm run lint
        npm test

    - name: Fetch Mocha report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: report
        path: 'report'
